Profile
Pinnit-UBC/pinnit-ubc pull request #16
Opened 2024-12-21 00:14 UTC by bigman-503

## Summary of Pull Request
User Profile Page
- Added a functional profile page (/profile) where users can view and edit their information, including:
- First Name, Last Name, Email, Username, Year Level, Faculty, Keywords, and Following.
- Integrated profile picture upload functionality with real-time preview.
- Profile pictures are securely uploaded to AWS S3 and served via CloudFront.
- User Authentication System

User Signup:
- Multi-step registration form:
    Step 1: Collects basic information (First Name, Last Name, Email, and Password).
    Step 2: Allows users to set a username, select year level, faculty, and upload a profile picture with a preview.
    Step 3: Enables users to select interests and hobbies via categories and custom keywords.
    Step 4: Recommends clubs based on selected keywords and interests, allowing users to follow clubs.
- Profile picture upload directly to AWS S3 with secure handling and caching optimizations.

User Login:
- Secure login endpoint with hashed password verification.
- User session management using JWT tokens stored as secure cookies.

Email Verification:
- Triggered during signup to verify the user’s email address.
- Prevents unauthorized access until the email is verified.

Session Management:
- Middleware checks for valid JWT tokens to protect routes.
- Sessions are managed with secure HTTP-only cookies for added security.

AWS Integration
- Configured AWS S3 bucket policies for secure storage of profile pictures.
- Updated code to use CloudFront URL for optimized delivery of assets.

Backend:
- Built endpoints for:
/api/profile: Handles CRUD operations for user profiles.
/api/userRegistration: Handles form submissions and email verification.
/api/login: Authenticates users and generates JWT tokens.
/api/validateSession: Validates active user sessions for protected routes.
- Supported secure handling of profile picture uploads and updates via AWS SDK.
- Integrated MongoDB for storing user credentials and profile data.

Security Highlights
- Password Security: User passwords are hashed using bcrypt for secure storage.
- JWT Tokens: Ensure stateless authentication and seamless session management.
- Secure Cookies: Protect sensitive data with HTTP-only and Secure flags.
- AWS S3 Integration: Configured bucket policies to protect user-uploaded profile pictures.

https://pinnit.atlassian.net/jira/core/projects/P1/board?selectedIssue=P1-72
https://pinnit.atlassian.net/jira/core/projects/P1/board?selectedIssue=P1-25

## Additional Comments
- Addressed bugs related to caching by appending timestamps to image URLs.
- Refactored code for better readability and maintainability.

2024-12-24 20:47 UTC, bcw117 requested changes
Lots of different features and changes for this PR. Since there were so many changes, I decided mostly focused on the backend changes and didn't look too closely at the frontend. We can make any needed fixes/changes to the FE another day. Take a look at the comments and lmk if you need any clarification.

2024-12-24 20:47 UTC, bcw117 commented on src/app/api/protected/protected-data.ts
Just a testing endpoint (I believe). If it works we can delete this file.

2024-12-24 20:47 UTC, bcw117 commented on src/app/api/registration/proxyImage.ts
> +export default async function handler(req: NextApiRequest, res: NextApiResponse) {
Handler convention. Also not sure what type of endpoint this is supposed to be, I'm assuming it's a GET so would rename function accordingly.

2024-12-24 20:47 UTC, bcw117 commented on src/app/api/registration/proxyImage.ts
Not sure if we would require an endpoint to retrieve an image buffer. We could make a function for it in the FE but not sure. We can keep it for now.

2024-12-24 20:47 UTC, bcw117 commented on src/app/api/registration/register-temp-user/route.ts
> +});
These should be apart of the lib folder. I would recommend separating amazon s3 and nodemailer logic from these endpoints and import the connections similar to how we have it with MongoDB (check db.ts and how it's database instance is shared across the backend). We should be able to access the s3 and transporter variable across backend.

2024-12-24 20:47 UTC, bcw117 commented on src/app/api/test-connection/route.ts
Similar comments to test-db.ts

2024-12-24 20:47 UTC, bcw117 commented on src/app/api/validateSession/route.ts
See validate-session.ts comments

2024-12-24 20:47 UTC, bcw117 commented on src/app/favicon.ico
Current have the Pinnit favicon on dev branch, try running `git merge dev` on your branch to resolve any conflicts

2024-12-24 20:47 UTC, bcw117 commented on src/app/layout.tsx
Small thing, would recommend keeping Pinnit as tab name 😆

2024-12-24 20:47 UTC, bcw117 commented on src/app/models/pinnitEvent.js
I believe we already have a models folder. To avoid redundancy,  import any models you have within the /lib/models folder.

2024-12-24 20:47 UTC, bcw117 commented on src/app/page.tsx
See _app.tsx comments

2024-12-24 20:47 UTC, bcw117 commented on src/app/profile/page.tsx
> +}
For interfaces and types, would recommend putting them in the /types folder if you think the type will be reused elsewhere in the project. run `git merge dev` to see the folder.

2024-12-24 20:47 UTC, bcw117 commented on src/models/Session.ts
For the models, move them to /lib/models folder since I believe we already have a models folder

2024-12-24 20:47 UTC, bcw117 commented on src/middleware.ts
I believe we should be authenticating all requests here and validating sessions here. See  src/app/api/authenticate/validate-session/validateSession.ts comments for more details

2024-12-24 20:47 UTC, bcw117 commented on src/lib/db.ts
A lot more robust then our connection method 👍

2024-12-24 20:47 UTC, bcw117 commented on src/components/FormSteps/Step1.tsx
For these step components, I would highly recommend renaming them to be less ambiguous so that it's more intuitive as to what these components do. From a developer perspective, I wouldn't know that the Step components would be related to user registration unless I dug into the code.

2024-12-24 20:47 UTC, bcw117 commented on src/app/utils/db.js
Already have a db connection function so this one is unneeded

2024-12-24 20:47 UTC, bcw117 commented on public/data/clubs.json
Not sure about the practicality of storing all the club information and followers in an almost 4000 line json. Might be better to store organization data in a database? Discuss further with team.

2024-12-24 20:47 UTC, bcw117 commented on output.css
Unsure what this file does lol

2024-12-24 23:24 UTC, bigman-503 commented on src/app/utils/db.js
file deleted

2024-12-24 23:24 UTC, bigman-503 commented on output.css
file deleted

2024-12-24 23:26 UTC, bigman-503 commented on package.json
> -    "dev": "next dev --turbopack",
Updated package.json

2024-12-25 01:38 UTC, bigman-503 commented on src/app/api/authenticate/login/route.ts
> +export default async function handler(req: NextApiRequest, res: NextApiResponse) {
fixed and updated login/route.ts

2024-12-25 01:39 UTC, bigman-503 commented on src/app/api/authenticate/logout/route.ts
> +  console.log('--- Logout Debugging ---');
debugging log is removed

2024-12-25 02:31 UTC, bigman-503 commented on src/app/api/db/test-db.ts
Good point. Test db file removed

2024-12-25 02:33 UTC, bigman-503 commented on src/app/api/profile/[id]/route.ts
> +export default async function handler(req: NextApiRequest, res: NextApiResponse) {
handler changed, file updated

2024-12-25 02:35 UTC, bigman-503 commented on src/app/api/profile/[id]/route.ts
> +  const { keywords, following } = req.body; // Expect keywords and following to be in the request body
implemented try-catch block!

2024-12-25 08:03 UTC, bigman-503 commented on src/app/api/profile/me/route.ts
> +export default async function handler(req: NextApiRequest, res: NextApiResponse) {
handler GET function switched to match convention

2024-12-25 14:17 UTC, bigman-503 commented on src/app/api/profile/me/route.ts
> +}
fixed!

2024-12-27 03:54 UTC, bigman-503 commented on src/app/api/authenticate/route.ts
api/authenticate/route.ts endpoint removed and parts moved to api/authenticate/login/route.ts

2024-12-27 03:58 UTC, bigman-503 commented on src/app/api/getAllClubs/route.ts
updated to /Users/richardluo/PinnitUBC/pinnit-ubc/src/app/api/clubs

2024-12-27 03:59 UTC, bigman-503 commented on src/app/api/getAllClubs/route.ts
updated to /Users/richardluo/PinnitUBC/pinnit-ubc/src/app/api/categories

2024-12-27 04:00 UTC, bigman-503 commented on src/app/api/getCategories/route.ts
updated to /Users/richardluo/PinnitUBC/pinnit-ubc/src/app/api/categories

2024-12-27 05:50 UTC, bigman-503 commented on src/app/api/registration/proxyImage.ts
> +export default async function handler(req: NextApiRequest, res: NextApiResponse) {
Handler updated!

2024-12-27 05:54 UTC, bigman-503 commented on src/app/api/registration/register-temp-user/route.ts
> +});
New files created and seperated register-temp-user/route:

/Users/richardluo/PinnitUBC/pinnit-ubc/src/lib/mailer.ts
/Users/richardluo/PinnitUBC/pinnit-ubc/src/lib/s3.ts

2024-12-27 06:29 UTC, bigman-503 commented on src/app/api/profile/me/route.ts
> +  await new Promise((resolve) => authenticateUser(req, res, resolve));
Fixed!

2024-12-27 06:33 UTC, bigman-503 commented on src/app/api/protected/protected-data.ts
file removed

2024-12-27 06:44 UTC, bigman-503 commented on src/app/api/test-connection/route.ts
good catch file deleted

2024-12-27 06:46 UTC, bigman-503 commented on src/app/api/validateSession/route.ts
redundant file deleted

2024-12-27 06:52 UTC, bigman-503 commented on src/app/layout.tsx
tab name changed

2024-12-27 06:55 UTC, bigman-503 commented on src/app/models/pinnitEvent.js
pinnitEvent.js moved to src/lib/models/pinnitEvent.js

2024-12-27 06:58 UTC, bigman-503 commented on src/app/_app.tsx
file deleted!

2024-12-27 07:01 UTC, bigman-503 commented on src/app/page.tsx
file removed

2024-12-27 07:06 UTC, bigman-503 commented on src/models/Session.ts
models moved to lib/models folder

2024-12-27 07:08 UTC, bigman-503 commented on public/data/clubs.json
signup.tsx is pulling clubs and category data from google sheets tab, this file is redundant but acts as a place holder for future json data

2024-12-27 22:15 UTC, bcw117 approved these changes
There are a few small things that weren't addressed in the edits made to PR but I'm still gonna merge this in since everything is working fine.

2024-12-27 22:16 UTC, merged